### ISSUE TITLE
faster CI integration tests

### ISSUE THREAD

**Issue by bengreenier** [RainwayApp/node-clangffi#24]
The current CI "integration" test is to walk libclang v13 and ensure we find the same types in it each time. This is good for ensuring we can always regenerate `libclang-bindings` using `libclang-bindings` but probably doesn't need to happen for validation of a PR, given it takes upwards of 15m in CI.

We should instead introduce a smaller integration test(s) that give us similar confidence, but execute much more quickly. Further, rather then just removing the existing one, we could consider instead running that only on check-in to `main` (after PR has been merged) for added confidence, but without slowing down the inner loop.

**Comment by lynn** [comment]
Fixed in #50: there's a smaller snapshot test for TypeScript codegen now.
